// <auto-generated />
using System;
using System.Collections.Generic;
using GED.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GED.Infrastructure.Migrations
{
    [DbContext(typeof(GedDbContext))]
    [Migration("20260307092924_AddDocumentAclExpiresAt")]
    partial class AddDocumentAclExpiresAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GED.Core.Models.DocumentAcl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("GrantedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by");

                    b.Property<int>("Permission")
                        .HasColumnType("integer")
                        .HasColumnName("permission");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "UserId")
                        .HasDatabaseName("ix_acl_doc_user");

                    b.ToTable("document_acls", (string)null);
                });

            modelBuilder.Entity("GED.Infrastructure.Data.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("document_date");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("FileHash")
                        .HasColumnType("text")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<bool>("IsOcrProcessed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ocr_processed");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.Property<string>("OcrText")
                        .HasColumnType("text")
                        .HasColumnName("ocr_text");

                    b.Property<Guid?>("ParentDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_document_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<List<string>>("Tags")
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_documents_category");

                    b.HasIndex("ContentType")
                        .HasDatabaseName("ix_documents_content_type");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_documents_created_at");

                    b.HasIndex("DocumentDate")
                        .HasDatabaseName("ix_documents_document_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_documents_status");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("GED.Infrastructure.Data.DocumentMetadataEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_metadata_document_id");

                    b.HasIndex("DocumentId", "Key")
                        .HasDatabaseName("ix_document_metadata_doc_key");

                    b.ToTable("document_metadata", (string)null);
                });

            modelBuilder.Entity("GED.Infrastructure.Data.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_outbox_unprocessed");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("GED.Infrastructure.Data.DocumentMetadataEntity", b =>
                {
                    b.HasOne("GED.Infrastructure.Data.DocumentEntity", "Document")
                        .WithMany("DocumentMetadata")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("GED.Infrastructure.Data.DocumentEntity", b =>
                {
                    b.Navigation("DocumentMetadata");
                });
#pragma warning restore 612, 618
        }
    }
}
